name: Docker Build and Push

on:
  push:
    branches: ["main"]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Generate .env file
          run: |
            cp ./apps/dokploy/.env.production.example ./.env.production

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
        - name: Build fresh base image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: |
              alexdev404/dokploy-containerized:latest
            platforms: linux/amd64
        - name: Build and tag registry image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile.local
            push: true
            tags: |
              alexdev404/dokploy:${{ github.ref_name == 'main' && 'latest' || 'canary' }}
            platforms: linux/amd64
